spring:
  datasource:
    url: jdbc:mysql://localhost:3307/adm_videos?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456
  flyway:
    enabled: true
    locations: classpath:db/migration